INSERT INTO my_dog.BREED (BREED_ID, DESCBREED) VALUES (1, 'LABRADOR');
INSERT INTO my_dog.BREED (BREED_ID, DESCBREED) VALUES (2, 'PASTOR');
INSERT INTO my_dog.BREED (BREED_ID, DESCBREED) VALUES (3, 'GOLDEN');