CREATE TABLE breed (BREED_ID bigint(9) NOT NULL AUTO_INCREMENT, DESCBREED varchar(200), PRIMARY KEY (BREED_ID)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE dog (DOG_ID bigint(9) NOT NULL AUTO_INCREMENT, NAME varchar(200), BREED_ID bigint(9), PRIMARY KEY (DOG_ID)) ENGINE=InnoDB DEFAULT CHARSET=latin1;

