-- breed inserts
INSERT INTO BREED (BREED_ID, DESCBREED) VALUES (1, 'LABRADOR');
INSERT INTO BREED (BREED_ID, DESCBREED) VALUES (2, 'PASTOR');
INSERT INTO BREED (BREED_ID, DESCBREED) VALUES (3, 'GOLDEN');
-- dogs inserts
INSERT INTO DOG (DOG_ID, NAME, BREED_ID) VALUES (1, 'Drica', 1);
INSERT INTO DOG (DOG_ID, NAME, BREED_ID) VALUES (2, 'Moca', 1);
INSERT INTO DOG (DOG_ID, NAME, BREED_ID) VALUES (3, 'Oslo', 2);
INSERT INTO DOG (DOG_ID, NAME, BREED_ID) VALUES (4, 'Bebel', 2);
INSERT INTO DOG (DOG_ID, NAME, BREED_ID) VALUES (5, 'Leoa', 2);
INSERT INTO DOG (DOG_ID, NAME, BREED_ID) VALUES (6, 'Meme', 3);
INSERT INTO DOG (DOG_ID, NAME, BREED_ID) VALUES (7, 'Ozzy', 1);